config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  unauthenticated do
    root :to => 'application#homepage'
  end

  authenticated do
    root :to => 'posts#index'
  end

  get 'application/close'

  get '/profiles/:id/followers', to: 'profiles#followers', as: "followers"
  get '/profiles/:id/followees', to: 'profiles#followees', as: "followees"

  get 'profiles/show'
  get 'stalk_zones/show'
  post '/followings', to: 'followings#create', as: 'create_following'
  delete '/followings', to: 'followings#destroy', as: 'unfollow'
  devise_for :users do
  end
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :followee, foreign_key: "followee_id", class_name: "User"
  belongs_to :follower, foreign_key: "follower_id", class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :follower_follows, class_name: "Following", foreign_key: :followee_id
  has_many :followers, through: :follower_follows, source: :follower
  has_many :followee_follows, class_name: "Following", foreign_key: :follower_id
  has_many :followees, through: :followee_follows, source: :followee

  validates :name, presence: true

  def self.find_all_by(search)
    self.all.select { |name| name.name.downcase == search.downcase}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :remember_me])
    devise_parameter_sanitizer.permit(:log_in, keys: [:name, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :bio, :location])
  end

  def current_user_follows?
    @user = User.find(params[:id])
    current_user.followees.include?(@user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    flash[:success] = "Comment Posted!"
    redirect_to @post
  end

  def destroy
    @post = Post.find_by_id(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = "Comment Deleted!"
    redirect_to @post
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.followees << @user
    redirect_back fallback_location: root_path
  end

  def destroy
    @user = User.find(params[:user_id])
    @following = Following.find_by(follower_id: current_user.id, followee_id: @user.id)
    @following.destroy
    redirect_back fallback_location: root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = current_user.posts.new
    @followees = current_user.followees.ids << current_user.id
    @posts = Post.where(user_id: @followees).all.order('created_at DESC')
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.create(post_params)
    flash[:success] = 'Your post has been published'
    redirect_back fallback_location: root_path
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comment = Comment.new
  end

  def edit
     @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    @post.update(post_params)
    flash[:success] = 'Post updated!'
    redirect_to @post
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    flash[:success] = 'Post destroyed!'
    redirect_to '/posts'
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by_id(params[:id])
    @posts = @user.posts.order('created_at DESC')
    @post = current_user.posts.new
    @current_user_does_not_follow = !current_user_follows?
    @current_user_follows = current_user_follows?
  end

  def followees
    @user = User.find_by_id(params[:id])
    @user.followees
  end
  def followers
    @user = User.find_by_id(params[:id])
    @user.followers
  end
end

app/controllers/stalk_zones_controller.rb
class StalkZonesController < ApplicationController
  before_action :authenticate_user!

  def show
    if params[:search]
      @users = User.find_all_by(params[:search])
    else
     @users = User.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/friend_zones_helper.rb
module FriendZonesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/application/close.html.erb
<div style="margin-bottom: 20px;">
<%= image_tag("https://github.com/linh4/stalk-zone/blob/master/app/assets/images/suckpic.jpg?raw=true") %>
</div>
<a href="<%= root_path %>" class="btn btn-dark btn-lg" role="button" style="margin-left: 250px;">Go Back</a>

app/views/application/homepage.html.erb
<div class="text-box">
  <div class="texts">
    <h1>Welcome to StalkZone</h1>
    <h3>Are you an Access Lab Member?</h3>
    <div class="button-box">
      <a href="/users/sign_in" class="btn btn-danger btn-lg" role="button" aria-pressed="true">Yes Yes Yes Let Me In</a>
      <a href="/application/close" class="btn btn-dark btn-lg" role="button" aria-pressed="true">No I suck</a>
    </div>
  </div>
</div>

<div class="welcome-page">
</div>

app/views/comments/_comment.html.erb
<div>
    <h4><%= link_to "#{comment.user.name}", profiles_show_path( id: comment.user_id) %></h4>
    <p><%= time_ago_in_words(comment.created_at) %> ago.</p>
    <hr>
    <div>
        <p><%= comment.content %></p>
        <% if current_user.id === comment.user_id %>
            <%= link_to "Delete", [comment.post, comment], method: :delete%>
        <% elsif current_user.id === comment.post.user_id %>
            <%= link_to "Delete", [comment.post, comment], method: :delete%>
        <% end %>
    </div>
    <hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stalk Zone</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= posts_path %>">
      <%= image_tag("https://raw.githubusercontent.com/linh4/stalk-zone/master/app/assets/images/friend-zone.png", :class => "img-logo") %>
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= posts_path %>">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= profiles_show_path(:id => current_user.id) %>">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= stalk_zones_show_path %>">Search</a>
      </li>
    </ul>
    <ul class="navbar-nav mr-sm-2">
    <li class="nav-item">
      <a class="nav-link" <%= link_to "Log Out", destroy_user_session_path, method: :delete %></a>
    </li>
  </ul>
  </div>
</nav>
<% end %>

<!-- FLASH MESSAGES -->
<div>
  <% flash.each do |key, value| %>
    <div>
      <%= value %>
    </div>
    <% end %>
  </div>
  <%= yield %>

</div>



</body>
</html>

app/views/posts/_comment_form.html.erb
<%= form_for [@post, @post.comments.new] do |f| %>
  <div style="display:inline">
    <%= f.text_area :content, style: "width: 60%", placeholder: "Leave a comment", rows: 3, id: "comment_form" %>
    <%= f.submit "Comment", class: "btn btn-danger", style: "margin-bottom: 30px;" %>
  </div>
<% end %>

app/views/posts/_post_form.html.erb
<div class="post-box">
  <%= form_for @post do |f| %>
  <div>
    <%= f.text_area :content, class: "text-area", rows: 4, placeholder: "What are you thinking now?"%>
    <%= f.submit "Post", class: "btn btn-danger" %>
  </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="post-box" style="text-align: center; margin-top: 30px;">
  <%= form_for @post do |f| %>
  <div>
    <%= f.text_area :content, class: "text-area", style: "width: 40%", rows: 4, placeholder: "Whats on your mind?"%>
    <%= f.submit "Post", class: "btn btn-danger", style: "margin-bottom: 30px;" %>
  </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<!-- News Feed -->
<di class="container">
  <div class="row justify-content-center">
    <div class="col-4">

      <h1 style="font-family: 'Monoton', cursive; color: #FF7373; font-size: 4em;">StalkZone</h1>

      <div><%= image_tag("friend-zone.png") %></div>

      <%= render "post_form" %>

      <% @posts.each do |post| %>
      <div class="posted">
        <div class="content-box">
          <h4><%= link_to "#{ post.user.name.capitalize }", profiles_show_path(id: post.user_id) %></h4>
          <%= time_ago_in_words(post.created_at) %> ago.
        </div>
          <hr>
        <div class="content-box">
          <p><%= post.content %> </p>
          <% if current_user.id === post.user_id %>
            <%= link_to edit_post_path(post) do %>
              <i class="fas fa-marker"></i>
            <% end %>
            <%= link_to post_path(post), method: :delete, data: {confirm: 'are you sure?'} do %>
              <i class="fas fa-trash"></i>
            <% end %>
          <% end %>
          <!-- Comment button -->
          <%= link_to post_path(post) do %>
            <i class="fa fa-comment"></i>
          <% end %>
        </div>

      </div>
      <% end %><!-- end main loop -->

    </div> <!-- end col -->
  </div> <!-- end row -->
</di><!-- end div container -->

app/views/posts/new.html.erb
<%= render 'post_form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">

      <div class="posted p-top">
        <div class="content-box">
          <h4><%= link_to @post.user.name.capitalize, profiles_show_path(id: @post.user_id) %></h4>
          <p><%= time_ago_in_words(@post.created_at) %> ago.</p>
          </div>
        <hr>

        <div class="content-box">
        <p><%= @post.content %> </p>
        <% if current_user.id === @post.user_id %>
          <%= link_to edit_post_path(@post) do %>
            <i class="fas fa-marker"></i>
          <% end %>
          <%= link_to post_path(@post), method: :delete, data: {confirm: 'are you sure?'} do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>

      </div>
    </div>

    <div class="posted-cmt">
      <div class="content-box">
        <!-- comments -->
        <h4 style="text-align:center">Comments</h4>
        <!-- comments loop -->
        <% @post.comments.each do |comment| %>
          <h4><%= link_to "#{ comment.user.name.capitalize }", profiles_show_path( id: comment.user_id) %></h4>
          <p><%= time_ago_in_words(comment.created_at) %> ago.</p>

          <p><%= comment.content %></p>
          <% if current_user.id === comment.user_id %>
            <%= link_to [ comment.post, comment], method: :delete, remote: true do %>
              <i class="fas fa-trash"></i>
            <% end %>
          <% elsif current_user.id === comment.post.user_id %>
            <%= link_to [ comment.post, comment], method: :delete, remote: true do %>
              <i class="fas fa-trash"></i>
            <% end %>
          <% end %>
          <hr>
          <% end %><!-- end comments loop -->
          <%= render 'comment_form' %>
        </div>
      </div><!-- end comment -->
    </div>


    </div>
  </div>
</div>

app/views/profiles/_post_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
  <div class="post-box">
    <div>
        <%= f.text_area :content, class: "text-area", rows: 5, placeholder: "What are you thinking now?" %>
        <%= f.submit "Post", class: "btn btn-danger" %>
      </div>
<% end %>

</div>

app/views/profiles/_profile_form.html.erb
<!-- Profile details -->
<%= image_tag("https://raw.githubusercontent.com/linh4/stalk-zone/master/app/assets/images/na-#{@user.id}.jpg", size: "300x400") %>
<h3><%= @user.name.capitalize %></h3>
<h5>Lives in: <%= @user.location %></h5>
<h4>Bio: </h4>
<h5><%= @user.bio %></h5>
<hr>
<% if @user.id === current_user.id %>
  <%= link_to "Edit Profile", edit_user_registration_path(), class: "btn btn-danger"%>
<% elsif @current_user_does_not_follow %>
  <%= link_to "Follow", create_following_path(user_id: @user.id), method: :post, class: "btn btn-danger"  %>

<% elsif @current_user_follows %>
  <%= link_to "Unfollow", unfollow_path(user_id: @user.id), method: :delete, class: "btn btn-danger"  %>
<% end %>

app/views/profiles/followees.html.erb
<h3 class="fff">Followees</h3>
<% @user.followees.each do |followee| %>
  <div class="row follow-row">
    <ul class="follow-people">
      <li>
        <%= image_tag("https://raw.githubusercontent.com/linh4/stalk-zone/master/app/assets/images/na-#{followee.id}.jpg", size: "100x100") %>
        <%= link_to followee.name.capitalize, profiles_show_path(id: followee.id) %>
      </li>
    </ul>
  </div>
<% end %>

app/views/profiles/followers.html.erb
<h3 class="fff">Followers</h3>
<% @user.followers.each do |follower| %>
  <div class="row follow-row">
    <ul class="follow-people">
      <li>
        <%= image_tag("https://raw.githubusercontent.com/linh4/stalk-zone/master/app/assets/images/na-#{follower.id}.jpg", size: "100x100") %>
        <%= link_to follower.name.capitalize, profiles_show_path(id: follower.id) %>
      </li>
    </ul>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row justify-content-between">

    <div class="col-3">
      <%= render 'profile_form'%>
    </div>

    <div class="col-5 custom-col">
      <!-- Users posts -->
      <% if @user.id === current_user.id %>
        <%= render "post_form" %>
      <% end %>

      <% @posts.each do |post| %>
        <div class="posted">
          <div class="content-box">
            <h4><%= link_to "#{ post.user.name.capitalize }", profiles_show_path(id: post.user_id) %></h4>
            <%= time_ago_in_words(post.created_at) %>
            ago.
          </div>
          <hr>
          <div class="content-box">
            <p><%= post.content %>
            </p>
            <% if current_user.id == post.user_id %>
              <%= link_to edit_post_path(post) do %>
              <i class="fas fa-marker"></i>
            <% end %>
            <%= link_to post_path(post), method: :delete, data: {confirm: 'are you sure?'} do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
        <!-- Comment button -->
        <%= link_to post_path(post) do %>
          <i class="fa fa-comment"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<!-- show followers and followees -->
<div class="col-3 friend-col">
  <h3>Following</h3>
    <div class="follows">
        <%= link_to "Followers", followers_path(@user), class: "link" %>
        <span><%= @user.followers.length %></span>
    </div>
    <div class="follows">
      <%= link_to "Followees", followees_path(@user), class: "link" %>
      <span><%= @user.followees.length %></span>
    </div>
</div>

app/views/stalk_zones/show.html.erb
<di class="container">
  <div class="row">
    <div class="col-12 search-box">
      <%= form_tag(stalk_zones_show_path, method: "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search" %>
        <%= submit_tag("Search", class: "btn btn-danger") %>
      <% end %>
    </div>
  </div> <!-- end col -->

  <div class="container">
    <div class="row justify-content-between">
  <!-- Users who are not friends -->
    <div class="col-12 fe-col">
      <h3>Find People</h3>
      <hr>
        <% @users.each do |user| %>
          <% if user.id != current_user.id %>
          <ul class="people-name">
            <li style="display: inline-block">
              <%= link_to user.name.capitalize, profiles_show_path(id: user.id) %>
            </ul>
          <% end %>
        <% end %>
      </div>

  </div> <!-- end row -->
</di><!-- end div container -->